# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20161025_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
